In [ ]:
import numpy as np

In [ ]:
# 1. Array Creation
# Create a NumPy array of numbers from 1 to 20. Then print its size.

a = np.arange(20)
print(a)
print(a.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20


In [ ]:
# 2. Zeros & Ones
# Create:

# a 3×4 array filled with zeros

x = np.zeros((2,3),dtype="int")
print(x)

# a 2×5 array filled with ones

y = np.ones((2,5),dtype="int")
print(y)

[[0 0 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# 3. Full Function
# Create a 4×4 array where every value is 7 using NumPy.

x = np.full((4,4),7)
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# 4. Reshape
# Create an array from 1 to 12 and reshape it into:

a = np.arange(1,13)
print(a)

# 3×4

a2 = a.reshape(3,4)
print(a2)
print(a2.shape)

# 2×6

a3 = a.reshape(2,6)
print(a3)
print(a3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
# 5. Flatten
# Take a 3×3 matrix and convert it into a 1D array using flatten.

a = np.arange(9).reshape(3,3)
print(a)

a1 = a.flatten()
print(a1)
print(a1.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
(9,)


In [ ]:
# 6. Arrange (arange)
# Create an array starting from 10 to 50 with a step of 5.

a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [ ]:
# 7. Sum of Elements
# Given array:
# [10, 20, 30, 40, 50]
# Find:

# total sum

a = [10, 20, 30, 40, 50]
ans = np.sum(a)
print(ans)

# sum of first 3 elements only


ans1 = np.sum(a[:3])
print(ans1)

150
60


In [ ]:
# 8. Matrix Addition
# Add the following two arrays:

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

print(A+B)

[[7 7 7]
 [7 7 7]]


In [ ]:
# 9. Matrix Subtraction
# Subtract array B from array A (from Q8).

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

print(B-A)

[[ 5  3  1]
 [-1 -3 -5]]


In [ ]:
# 10. Element-wise Multiplication
# Multiply arrays A and B element by element.

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

print(A*B)

[[ 6 10 12]
 [12 10  6]]


In [ ]:
# 11. Mean
# Find the mean of:

a = [12, 15, 20, 25, 30]
ans = np.mean(a)
print(ans)

20.4


In [ ]:
# 12. Median
# Find the median of:

a = [5, 2, 9, 1, 7, 6]
ans = np.median(a)
print(ans)

5.5


In [ ]:
# 13. Standard Deviation
# Find the standard deviation of:

a = [4, 8, 6, 5, 3, 7]
ans = np.std(a)
print(ans)

1.707825127659933


In [ ]:
# 14. Row-wise Sum
# Given matrix:

# Find sum of each row separately.

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
ans2 = np.sum(a,axis=0)
print(a)
print(ans2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [ ]:
# 15. Column-wise Sum
# Using the same matrix from Q14, find sum of each column.

ans3 = np.sum(a,axis=1)
print(a)
print(ans3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [ ]:
# 16. Reshape + Mean
# Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.

a = np.arange(1,17).reshape(4,4)
print(a)
ans = np.mean(a,axis=1)
print(ans)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2.5  6.5 10.5 14.5]


In [ ]:
# 17. Flatten + Size
# Create a 5×5 ones matrix. Flatten it and find its size.

a = np.ones(25).reshape(5,5)
print(a)
a1 = a.flatten()
print(a1)
print(a1.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
25


In [ ]:
# 18. Arithmetic Combination
# Given:

# Compute:
# (A + B) * 2

A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

ans = ((A+B)*2)
print(ans)

[12 16 20 24]


In [ ]:
# 19. Mixed Operations
# Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.

a = np.arange(1,10).reshape(3,3)
ans = (a*5)
ans2 = sum(ans)
print(a)
print(ans)
print(ans2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[60 75 90]


In [ ]:
# 20. Statistics Combo
# Given:
# Find:

# mean

# median

# standard deviation

a = np.array([15, 18, 21, 24, 27, 30])
print(np.mean(a))
print(np.median(a))
print(np.std(a))

22.5
22.5
5.123475382979799


In [ ]:
# hard

# 1. Advanced Reshape + Sum

# Create an array from 1 to 48.
# Reshape it into 4 × 4 × 3.
# Find:

# sum along axis 0

# sum along axis 1

# sum along axis 2

a = np.arange(1,49).reshape(4,4,3)
print(a)
ans = np.sum(a,axis=0)
ans2 = np.sum(a,axis=1)
ans3 = np.sum(a,axis=2)
print(ans)
print(ans2)
print(ans3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


In [ ]:
# 2. Conditional Replacement

# Create array from 1 to 20.
# Replace all numbers:

# divisible by 3 → -1

# divisible by 5 → 100

# (Do it using NumPy, not loops.)

a = np.arange(1,21)
print(a)

a = np.where(a%3==0,-1,a)
a = np.where(a%5==0,100,a)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


In [ ]:
# 2. Conditional Replacement

# Create array from 1 to 20.
# Replace all numbers:

# divisible by 3 → -1

# divisible by 5 → 100

# (Do it using NumPy, not loops.)

a = np.arange(1,21)
print(a)

a[a%3 ==0] = -1
a[a%5 ==0] = 100
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


In [ ]:
# 3. Broadcasting Math

# Given:

# Add B to every row of A using broadcasting.

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

B = np.array([10,20,30])

ans = A + B
print(ans)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
# 4. Flatten vs Ravel Logic

# Create a 3×3 matrix.
# Use ravel() to flatten and modify the first element.
# Then check whether original array changes.
# Explain why.

# ----------------------------------------------------------------------------------

import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = a.ravel()      # flatten using ravel
b[0] = 100         # modify first element

print("Flattened array:", b)
print("Original array:\n", a)

Flattened array: [100   2   3   4   5   6   7   8   9]
Original array:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
# 5. Indexing Challenge

# Create array 1–25 and reshape to 5×5.
# Extract:

a = np.arange(1,26).reshape(5,5)
print(a)

# middle row
print(a[2:3])

# last column
print(a[: ,-1])

# corner elements only
print(a[0,0],
      a[0,4],
      a[4,0],
      a[4,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12 13 14 15]]
[ 5 10 15 20 25]
1 5 21 25


In [ ]:
# 6. Statistical Axis Problem

# Given:

# Find:

# mean of each column

# standard deviation of each row

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
ans = np.mean(arr)
ans2 = np.std(arr)

print(ans)
print(ans2)

50.0
25.81988897471611


In [ ]:
# 7. Matrix Arithmetic Combo

# Create two random 3×3 arrays.
# Compute:

# (A + B) * 2 - A

A = np.arange(1,10).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

print(A)
print(B)
ans = (A + B) * 2 - A
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
# 8. Pattern Matrix

# Create this matrix using NumPy only:

# [[1,0,1,0],
#  [0,1,0,1],
#  [1,0,1,0],
#  [0,1,0,1]]

# (No manual typing.)

a = np.arange(16).reshape(4,4)%2
a[::2] = 1 - a[::2]
print(a)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [ ]:
# 9. 3D Array Stats

# Create array from 1–27 and reshape to 3×3×3.
# Find:

# overall mean

# mean along axis 0

# median of entire array

a = np.arange(1,28).reshape(3,3,3)
print(a)
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.median(a))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
14.0
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
14.0


In [ ]:
# 10. Multi-step Transformation

# Create array from 1–16.
# Steps:

# Reshape to 4×4

# Multiply each column by [1,2,3,4]

# Flatten result

# Find standard deviation

import numpy as np

a = np.arange(1,17).reshape(4,4)

b = np.array([1,2,3,4])

a1 = a * b
a2 = a1.flatten()

print(a)
print(a1)
print(a2)
print(a2.shape)
print(np.std(a2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]
[ 1  4  9 16  5 12 21 32  9 20 33 48 13 28 45 64]
(16,)
17.38533865071371
